### ISSUE TITLE
Creation of the individual driver account

### ISSUE THREAD

**Issue by Moimou** [BuildForSDGCohort2/Team-291-Frontend#3]
individual driver account must contains his name, company, category(individual or fleet), a generated number.
it must also have an area for the list of his breakdowns and after each listed breakdown
-1 button for his localozation on map
-1 button for state
-1 button for bills ( this button will appear only if the bills exist and will have red color if the bills is not yet paid)

Please guys do this on two days if possible so that we can continue with the same format for others account. 
Courage guys. we count on you

**Comment by twabi** [comment]
the sign up and sign in pages for the driver as well as home layout were successfully created. No functionalities implemented though
